### PR TITLE
Release Version 1.0

### LINKED ISSUE #15: Fix code points of modified graphemes
# Found 12 generated graphemes
| Grapheme | Grapheme-UC | BIPA | BIPA-UC | Modified | Segments | Graphemes | Count |
|:-----------|:---------------------|:-------|:---------------------|:-----------|:-------------|:------------|--------:|
| ue | U+0075 U+0065 | ue | U+0075 U+0065 | | b ue l ɛ | vwelë. | 1 |
| uiː | U+0075 U+0069 U+02d0 | uiː | U+0075 U+0069 U+02d0 | | uiː j aː n i | ui:yá:ni | 1 |
| ʁ’ | U+0281 U+2019 | ʁʼ | U+0281 U+02bc | * | h i s ʁ’ u n | hisγ'un | 1 |
| ua | U+0075 U+0061 | ua | U+0075 U+0061 | | k ua | cua | 2 |
| sʰ | U+0073 U+02b0 | sʰ | U+0073 U+02b0 | | oː χ sʰ a | ó:χsʰá | 2 |
| ie | U+0069 U+0065 | ie | U+0069 U+0065 | | v ie n t o | viento | 3 |
| oi | U+006f U+0069 | oi | U+006f U+0069 | | k oi ʎ u r | coyllur | 9 |
| s̺ | U+0073 U+033a | s̺ | U+0073 U+033a | | s̺ i p a s̺ | ʃipas | 18 |
| r̝ | U+0072 U+031d | r̝ | U+0072 U+031d | | r̝ u k u | řuku | 20 |
| ui | U+0075 U+0069 | ui | U+0075 U+0069 | | h u tʃ ui | huchuy | 39 |
| au | U+0061 U+0075 | au | U+0061 U+0075 | | m au k a | mawka | 113 |
| ai | U+0061 U+0069 | ai | U+0061 U+0069 | | h a n ai | hanay | 351 |
# Found 13 modified graphemes
| Grapheme | Grapheme-UC | BIPA | BIPA-UC | Segments | Graphemes | Count |
|:-----------|:---------------------|:-------|:---------------------|:---------------------|:-------------|--------:|
| q’ | U+0071 U+2019 | qʼ | U+0071 U+02bc | s u q’ u + n i | suq’uni | 1 |
| ds | U+0064 U+0073 | dz | U+0064 U+007a | k uː ds i | kú:dži | 1 |
| t’ | U+0074 U+2019 | tʼ | U+0074 U+02bc | t’ iː r a | t’í:r̂a | 1 |
| p’ | U+0070 U+2019 | pʼ | U+0070 U+02bc | p’ a e k e | p’aéke | 2 |
| ts’ | U+0074 U+0073 U+2019 | tsʼ | U+0074 U+0073 U+02bc | ts’ a: t + k a t n i | ts’á:t-kátni | 3 |
| k’ | U+006b U+2019 | kʼ | U+006b U+02bc | k’ e l j u | k’élyu | 6 |
| tʃ’ | U+0074 U+0283 U+2019 | tʃʼ | U+0074 U+0283 U+02bc | tʃ’ u s a | ch’usa | 9 |
| o: | U+006f U+003a | oː | U+006f U+02d0 | k a: l o: | ka:lo: | 10 |
| ʈʂ’ | U+0288 U+0282 U+2019 | ʈʂʼ | U+0288 U+0282 U+02bc | a s ʈʂ’ a | asĉ'a | 10 |
| u: | U+0075 U+003a | uː | U+0075 U+02d0 | p a: k u: | pá:ku: | 13 |
| e: | U+0065 U+003a | eː | U+0065 U+02d0 | ʃ e: k u | še:ku | 14 |
| i: | U+0069 U+003a | iː | U+0069 U+02d0 | t s i: | tsi: | 22 |
| a: | U+0061 U+003a | aː | U+0061 U+02d0 | k a: l o: | ka:lo: | 40 |
# Found 3 slashed graphemes
| Grapheme | Grapheme-UC | BIPA | BIPA-UC | Segments | Graphemes | Count |
|:-----------|:--------------|:-------|:----------|:------------------------|:------------|--------:|
| r/j | U+0072 | j | U+006a | t i j/r a + r/j i + n a | tirayina | 1 |
| j/r | U+006a | r | U+0072 | t i j/r a + r/j i + n a | tirayina | 1 |
| tʃ/k | U+0074 U+0283 | k | U+006b | k u tʃ/k u tʃ u | kukuchi | 1 |

### PR DESCRIPTION
**Pull request by Tarotis**
The draft for the paper is written and I just implemented the last changes on EDICTOR, especially in order to fix #15 . I implemented two changes: 

- U+2019 to U+02bc
- U+003a to U+02d0

However, when I want to check the profile, I receive a new error message. No transcription errors are reported for `makecldf`.

Command: `cldfbench lexibank.check_profile lexibank_crossandean.py --noprofile`

Error message:
```
Traceback (most recent call last):
  File "/Users/blum/Projects/venv/crossandean/bin/cldfbench", line 8, in <module>
    sys.exit(main())
  File "/Users/blum/Projects/venv/crossandean/lib/python3.8/site-packages/cldfbench/__main__.py", line 89, in main
    return args.main(args) or 0
  File "/Users/blum/Projects/venv/crossandean/lib/python3.8/site-packages/pylexibank/commands/check_profile.py", line 36, in run
    with_dataset(args, check_profile)
  File "/Users/blum/Projects/venv/crossandean/lib/python3.8/site-packages/cldfbench/cli_util.py", line 161, in with_dataset
    res = func(*arg, args)
  File "/Users/blum/Projects/venv/crossandean/lib/python3.8/site-packages/pylexibank/commands/check_profile.py", line 51, in check_profile
    sound = args.clts.api.bipa[tk]
  File "/Users/blum/Projects/venv/crossandean/lib/python3.8/site-packages/clldutils/misc.py", line 197, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/Users/blum/Projects/venv/crossandean/lib/python3.8/site-packages/pyclts/api.py", line 23, in bipa
    return self.transcriptionsystem('bipa')
  File "/Users/blum/Projects/venv/crossandean/lib/python3.8/site-packages/pyclts/api.py", line 80, in transcriptionsystem
    if key in self.transcriptionsystem_dict:
  File "/Users/blum/Projects/venv/crossandean/lib/python3.8/site-packages/clldutils/misc.py", line 197, in __get__
    result = instance.__dict__[self.__name__] = self.fget(instance)
  File "/Users/blum/Projects/venv/crossandean/lib/python3.8/site-packages/pyclts/api.py", line 77, in transcriptionsystem_dict
    return {ts.id: ts for ts in self.iter_transcriptionsystem()}
  File "/Users/blum/Projects/venv/crossandean/lib/python3.8/site-packages/pyclts/api.py", line 77, in <dictcomp>
    return {ts.id: ts for ts in self.iter_transcriptionsystem()}
  File "/Users/blum/Projects/venv/crossandean/lib/python3.8/site-packages/pyclts/api.py", line 69, in iter_transcriptionsystem
    yield TranscriptionSystem(
  File "/Users/blum/Projects/venv/crossandean/lib/python3.8/site-packages/pyclts/transcriptionsystem.py", line 77, in __init__
    raise ValueError(
ValueError: Unrecognized features (duration: ultra-long, line 129))
```

Does `duration: ultra-long` refer to `ː`? In any case, line 129 seems completely unaffected by the changes I made.. or is it line 129 within the transcription system, so implementing a print-statement within the pyclts module could provide hints on the source of the error? @LinguList Do you have a quick answer or suggestion on how to proceed with the debugging for this?

### CODE REVIEW

**Comment by LinguList** [comment]
@Tarotis, what COMMAND do you use to convert the data to CLDF, can you please provide this as well?

**Comment by LinguList** [comment]
A, I see, sorry: you do not provide the glottolog version, neither concepticon-version, neither clts version. This explains the failure, as your error pertains to CLTS.

**Comment by LinguList** [comment]
What happens is that you probably have checked out a CLTS version like 2.0 but your Python pyclts verion is expecting data from 2.1.0 or 2.2.0. This is when the ultralong problem usually occurs.

**Comment by LinguList** [comment]
I also suggest to release version 1.0 ONLY when the paper has been accepted for publication and you are sure to not modify it more. If the paper goes into review, I'd not release a 1.0.

**Comment by Tarotis** [comment]
I am tempted to create a Bart Simpson homework-assignment `I will always specify my CLDF versions explicitly`. Thank you!

**Comment by Tarotis** [comment]
This PR now also closes #15

**Review by LinguList — APPROVED** [review]

**Pull request merged**
